### ISSUE TITLE
 Error (Platform Toolset = 'v141') cannot be found

### ISSUE THREAD

**Issue by dacoppet** [MicrosoftDocs/mixed-reality#1055]
When following the tutorial, with Visual Studio 2019 installed as only IDE version when deploy the device on step 9 (Build your application to your device : https://docs.microsoft.com/en-us/windows/mixed-reality/mrlearning-base-ch1#build-your-application-to-your-device).
I have the following error: 
"
MSB8020	The build tools for Visual Studio 2017 (Platform Toolset = 'v141') cannot be found. To build using the v141 build tools, please install Visual Studio 2017 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution".	MixedRealityBase	C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets	
"
I solved it by changing The solution is: open menu "Project"-&gt;Properties-&gt;Configuration Properites-&gt;General - and choose platform toolset v142 (or latest available). 
You may want to put a note to warn customer or do a root cause analysis on the default value set for the platform toolset (set to VS2017 toolset140).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62d386bb-3f93-d434-e7b3-28c58ea673e9
* Version Independent ID: a1a9b02f-66a0-feb0-7a08-9a8d2cf398d1
* Content: [MR Learning Base Module - Project Initialization and First Application - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/mrlearning-base-ch1#build-your-application-to-your-device)
* Content Source: [mixed-reality-docs/mrlearning-base-ch1.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/mrlearning-base-ch1.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @jessemcculloch
* Microsoft Alias: **jemccull**

**Comment by LanceMcCarthy** [comment]
This is because Unity only uses IL2CPP now. Thus the generated VS project is CPP.Therefore, since VS2019 doesn't ship with the install the v141 toolset, you would need to install it under the Additional Components dialog

I would present two options to the user:

1. (permanent fix) Install the 141 toolset

This is a permanent solution that will prevent the error on every Unity-generated project (at least until Unity updates the project template they use).

![image](https://user-images.githubusercontent.com/3520532/57166525-5daf8880-6daf-11e9-9440-43827fbf7533.png)

2. (quick fix) Change the target toolset on every project they need to (using the steps @dacoppet mentions above). 

![image](https://user-images.githubusercontent.com/3520532/57167904-563eae00-6db4-11e9-9e14-f4ab4389c692.png)

**Comment by mr0ng** [comment]
@LanceMcCarthy and @dacoppet great feedback and solutions. We're currently updating the documentation with new screenshots and descriptions for the newer version of MRTK and VS2019, and will incorporate these for users. Thank you!
