### ISSUE TITLE
Indicator only works once

### ISSUE THREAD

**Issue by Arundelain** [MicrosoftDocs/mixed-reality#12]
Could you update the tutorial to make it so the indicator works more than once? When you look away the first time, the indicator is visible however, when you glance back at the explorer, the indicator becomes invisible but never turns visible again when you glance away again.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a77974e-95c6-8d98-08de-53c55ecf8600
* Version Independent ID: d60ba94b-87b2-6be0-1675-f4b2114b7bbd
* Content: [Getting started tutorials - 5. Creating dynamic content using Solvers - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/mr-learning-base-05)
* Content Source: [mixed-reality-docs/mr-learning-base-05.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-learning-base-05.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @jessemcculloch
* Microsoft Alias: **jemccull**

**Comment by hferrone** [comment]
@mr0ng @martinwilter Can you assist?

**Comment by hferrone** [comment]
@mr0ng @martinwilter Following up :)

**Comment by martinwilter** [comment]
@Arundelain, sorry about this! 

Quick fix: Remove the Directional Indicator Controller (Script) component, and it should work as expected.

__

The root of the issue:

In the tutorial 5. Creating dynamic content using Solvers > [Using the Directional Indicator Solver to direct the user to objects](https://docs.microsoft.com/en-us/windows/mixed-reality/mr-learning-base-05#using-the-directional-indicator-solver-to-direct-the-user-to-objects) instructions:

![image](https://user-images.githubusercontent.com/16746283/90432223-11a95580-e07f-11ea-902d-31633ad0858c.png)

the Directional Indicator Controller (Script) component should NOT be added at this point (but in the next tutorial '6. Creating a dynamic menu that follows the user'). This class simply disables the Indicator once the object is found. (This is so that later when the app user has access to the menu and speech commands, the Indicator is manually enabled when needed, so it does not show/hide for example when user is just walking around the experience and happen to look another way).

![image](https://user-images.githubusercontent.com/16746283/90431623-2df8c280-e07e-11ea-8e96-779ce7e60f28.png)

Once the Indicator is disabled, the Directional Indicator Solver will no longer work since the object is disabled.

__

Instead, the Directional Indicator Controller (Script) component should be added during tutorial 6. Creating user interfaces > [Creating a dynamic menu that follows the user](https://docs.microsoft.com/en-us/windows/mixed-reality/mr-learning-base-06#creating-a-dynamic-menu-that-follows-the-user) along with this step:

![image](https://user-images.githubusercontent.com/16746283/90432149-f9d1d180-e07e-11ea-9af5-72fdce1f1ed1.png)

__

@hferrone, we will make a PR to address this issue shortly.
