### ISSUE TITLE
BaseModule package V1.1 is incompatible with MRTK 2.1.

### ISSUE THREAD

**Issue by Charles-W4** [MicrosoftDocs/mixed-reality#1779]
I was able to mostly work around this issue by importing just the models/materials/textures. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a7e480f6-30d8-9538-bff1-74ba54dc310e
* Version Independent ID: 1cb31b72-b828-d8d3-74fa-6641a61f3750
* Content: [Getting started tutorials - 5. Interacting with 3D objects - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/mrlearning-base-ch4#feedback)
* Content Source: [mixed-reality-docs/mrlearning-base-ch4.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/mrlearning-base-ch4.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @jessemcculloch
* Microsoft Alias: **jemccull**

**Comment by martinwilter** [comment]
@Charles-W4 Sorry for the inconvenience. The BaseModuleAssets has been updated to work with MRKT 2.1. You can download the updated version by visiting step 2 of the [Organizing 3D Objects in a Collection](https://docs.microsoft.com/en-us/windows/mixed-reality/mrlearning-base-ch4#organizing-3d-objects-in-a-collection) section in the previous lesson:

> 2. Download the Unity package [BaseModuleAssets version 1.2.1](https://github.com/Developer-OI/MixedRealityLearning/releases/download/1.2.1/BaseModuleAssets-1.2.1.unitypackage) and import it using the same instructions to import custom packages outlined in [Lesson1](https://docs.microsoft.com/en-us/windows/mixed-reality/mrlearning-base-ch1). This package includes 3D models and other useful assets that are used throughout this tutorial.


@jessemcculloch This issue was addressed with PR #1816, commit https://github.com/MicrosoftDocs/mixed-reality/pull/1816/commits/aa536dd4e12d15a0371a124dab2430eaa5e098b6.
