### ISSUE TITLE
Won't new Edge be delivered via Windows Update on Jan 15?

### ISSUE THREAD

**Issue by mgol** [MicrosoftDocs/mixed-reality#2005]
According to https://docs.microsoft.com/en-us/deployedge/microsoft-edge-blocker-toolkit, the new Edge will be pushed to Windows 10 devices via Windows Update starting on January 15, 2020. However, this page suggests some issues with Mixed Reality right now and warns:

&gt; If you opt to download the new Microsoft Edge before taking these updates, there will be some known issues with its behavior in Windows Mixed Reality (which you can read about below).

"If you opt to" - will the new Edge be pushed automatically on January 15 or not then? Documentation seems unclear here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 383f994b-9170-6cd6-8603-ef94d6b659be
* Version Independent ID: db9b5a4c-6557-a100-5555-7c436e27fa2d
* Content: [Windows Mixed Reality and the new Microsoft Edge - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/new-microsoft-edge)
* Content Source: [mixed-reality-docs/new-microsoft-edge.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/new-microsoft-edge.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @mattzmsft
* Microsoft Alias: **mazeller**

**Comment by mattzmsft** [comment]
This article explains the rollout process: https://blogs.windows.com/msedgedev/2020/01/15/upgrading-new-microsoft-edge-79-chromium/

You can proactively download the new Edge beginning today from the website, but it will _not_ begin rolling out to customers via Windows Update immediately. That's why I wrote that Windows Mixed Reality customers may want to wait to install the new Microsoft Edge (either waiting until after the end of January to manually install it, or waiting for the automatic Windows Update rollout which will happen gradually over time). Either way, ideally you'll want to make sure you have the updates I mentioned on that page (from the 2020-01 Cumulative Update) before getting Edge. You shouldn't be getting it via Windows Update until after that Cumulative Update has arrived, so this is really only a warning for customers who opt to install it manually beginning today. Does that help?

**Comment by mattzmsft** [comment]
I'm hoping that addressed your question! Going to close this issue, but let me know if that didn't answer what you were asking.

**Comment by mgol** [comment]
Yes, that answers my question, thank you!
