### ISSUE TITLE
Missing steps before "Creating a dynamic menu that follows the user"

### ISSUE THREAD

**Issue by KenanBektas** [MicrosoftDocs/mixed-reality#202]
As far I can follow, some steps seem to be missing before the "Creating a dynamic menu that follows the user" part. Pressing the buttons (i.e., Hints or Explode) does not have an effect in the Game mode. The Hierarchy Window on the figure has "DontDestroyOnLoad" which is not explained in the tutorial. Where does that come from what is its function? Thanks.

**Comment by veeruby-developer** [comment]
@KenanBektas once the buttons(Hints and Explode) are configured as mentioned in the tutorial, Hints button will toggle the visibility of the placement hint objects and Explode button will toggle the exploded view on and off.

If you feel that some steps are missing can you please specify which are the missing steps so that we could update the tutorial if it is relevant.

**Comment by veeruby-developer** [comment]
@KenanBektas once the buttons(Hints and Explode) are configured as mentioned in the tutorial, Hints button will toggle the visibility of the placement hint objects and Explode button will toggle the exploded view on and off.
If you feel that some steps are missing can you please specify which are the missing steps so that we could update the tutorial if it is relevant. also "DontDestroyOnLoad" does not concern to this tutorial, you can find all the needed information hear [DontDestroyOnLoad](https://docs.unity3d.com/ScriptReference/Object.DontDestroyOnLoad.html)

**Comment by KenanBektas** [comment]
Thank you for responding.
Unfortunately, I can not say that specifically.
In my message, I tried to describe what I've observed while following the
tutorial.
Once I have time, I will start over and try to replicate it and let you
know.
PS: I just saw your message regarding the " DontDestroyOnLoad ". Thank you
for that.
