### ISSUE TITLE
No 360 Viewer Extension Installed

### ISSUE THREAD

**Issue by hubick** [MicrosoftDocs/mixed-reality#2026]
I'm on 1909 w 2020-01 (build 18363.628). I've tried installing via both MicrosoftEdgeSetup.exe and MicrosoftEdgeEnterpriseX64.msi, and neither results in edge://system/ listing any 360 Viewer extension. I've tried restarting Edge and my PC multiple times, but I've never been offered any icon to enter VR in YouTube 360 videos. If I revert to old Edge, I do see the icon from the old extension, and can use it to enter VR in my Reverb, but 360 videos are not displayed correctly (the screen is split into top/bottom views or something).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 383f994b-9170-6cd6-8603-ef94d6b659be
* Version Independent ID: db9b5a4c-6557-a100-5555-7c436e27fa2d
* Content: [Windows Mixed Reality and the new Microsoft Edge - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/new-microsoft-edge#feedback)
* Content Source: [mixed-reality-docs/new-microsoft-edge.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/new-microsoft-edge.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @mattzmsft
* Microsoft Alias: **mazeller**

**Comment by mattzmsft** [comment]
@hubick are you still experiencing this issue? 360 Viewer installs automatically when you install the _Stable_ channel version of the new Microsoft Edge. I'm not entirely sure which version you'd be getting by manually installing Edge as you reference. You won't see the extension listed because of the way it installs, but if it were installed correctly you _should_ see the 360 Viewer icon (a blue circle with a play arrow in the middle) to the right of your address bar. We're not seeing any issues with the install logic and any time customers have brought this issue up previously, the issue turned out to be that they weren't using the Edge Stable (or release) channel, they were using Dev, Beta, or Canary. The logic we use for install is detecting if you have the Windows Mixed Reality feature set installed (which if you're able to use your Reverb in the Windows Mixed Reality home, you should be set).

**Comment by hubick** [comment]
@mattzmsft I had been downloading the installer from the Edge website. I rebuilt a new PC and am not experiencing the issue on this new machine. Thanks.

**Comment by mattzmsft** [comment]
@hubick thanks for confirming! Sorry it took so long for me to address this. Just so you know for next time, please file product bugs via Feedback Hub so we see them immediately and can triage (and it'll also give us useful telemetry). In general, filing issues here on the developer documentation is used to let the documentation team know that there are mistakes in the docs, and so it takes much longer (if at all) for the product team to see product bugs reported here.
