### ISSUE TITLE
Event properties object field already has an object?

### ISSUE THREAD

**Issue by aprilspeight** [MicrosoftDocs/mixed-reality#2038]
In the 'Hand tracking gestures and interactable buttons' section, the image for step 4 (Configure the cube to receive the On Press event) shows that there is currently nothing existing in the Event Properties section for On Press (). However, I already see something listed there (I'll include a screenshot in a follow-up comment). Is the reader supposed to delete what's already there (using the - icon) and add a new one (using the + icon) and then drag and drop the Cube into the object field? OR should the reader leave what's there and use the + icon to add a new section for the cube? The same occurs in step 6 whereas there's already something there for the On Release () Event Properties section.

If the reader is supposed to delete what's already there, that may be confusing for beginners who are unfamiliar with Unity UI. Likewise, if they're suppose to use the + icon to add a new one in the Event Properties section, that may be confusing as well if they're unfamiliar with Unity UI.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ff554d8-c68d-28a2-1331-3177bc8f6d71
* Version Independent ID: a4419d7e-9355-76fd-4ca7-9ea26cb0a5aa
* Content: [Getting started tutorials - 3. Creating user interface and configure Mixed Reality Toolkit - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/mrlearning-base-ch2#creating-a-panel-of-buttons-using-mrtks-grid-object-collection)
* Content Source: [mixed-reality-docs/mrlearning-base-ch2.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/mrlearning-base-ch2.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @jessemcculloch
* Microsoft Alias: **jemccull**

**Comment by aprilspeight** [comment]
Here is the screenshot of what's seen in Unity before completing Step 4.
![hl2_tutorials_on_press_event](https://user-images.githubusercontent.com/34195866/74286084-ea428c00-4cdb-11ea-838a-8c16979543f6.PNG)

**Comment by martinwilter** [comment]
@aprilspeight Thanks for the feedback and the screenshot.

In this step, the reader is meant to use the two existing events and simply change the configuration from playing the ButtonPress and ButtonUnpress audio clips to having the cube change color. I can see that this might not be clear enough, and also it's not ideal to replace the default interaction sounds for no apparent reason, so I've made a note to have this updated to have the reader add new events instead of using the existing once.

We will make this update as soon as possible. Thanks again for the feedback, we appreciate it.

**Comment by aprilspeight** [comment]
Thanks, again! Loving the updates thus far. Everything reads pretty clearly.
