### ISSUE TITLE
Schemas namespaces not accurate

### ISSUE THREAD

**Issue by Holo-Fiedel** [MicrosoftDocs/mixed-reality#2099]
The package.appxmanifest in my solution only accepted the namespaces 
"http://..." for uap5 and uap6, not as documented on this page the "https://..." versions of it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 03eff217-9145-683b-86e6-3fee12ca90fd
* Version Independent ID: e56f3c19-6676-4e33-ac8c-6c3a461d4f71
* Content: [Implement 3D app launchers (UWP apps) - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/implementing-3d-app-launchers#feedback)
* Content Source: [mixed-reality-docs/implementing-3d-app-launchers.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/implementing-3d-app-launchers.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @thmignon
* Microsoft Alias: **thmignon**

**Comment by cefoot** [comment]
I second this.. took me quite some time to see that the [example](https://github.com/microsoft/Windows-universal-samples/blob/master/Samples/MixedRealityModel/cs/Package.appxmanifest) works because it uses the http protocol without the secure part.

Here is my pull request for this.
[Pull-Request](https://github.com/MicrosoftDocs/mixed-reality/pull/2122)

**Comment by jessemcculloch** [comment]
Closed with PR #2122
