### ISSUE TITLE
Build...Play....Connect Hololens?

### ISSUE THREAD

**Issue by bblackbourn** [MicrosoftDocs/mixed-reality#2125]
Apologies in advance if I'm missing something obvious, but having read the lesson overview and followed the configuration instructions I got to the end and didn't understand what was supposed to happen.  

The text has left me with a number of questions.

The pre-lesson overview reads:
_**By the end of this lesson, you'll be able to open the application on multiple devices and see the avatar, represented by a sphere for each person that joins.**_

**Question 1: You'll be able to open the Application** 
What application?  Unity (on multiple devices)?  A built & deployed solution/application via Unity/VS that has been copied or side-loaded to multiple PCs...or devices?  I don't think we create an application by the end of this lesson, just prep really.

The post-lesson summary reads:
_**Once all the steps above are complete and the build process is also complete, press the Play button and connect your HoloLens 2. You should see a sphere moving around as you move your head. This will be shown for any user that joins your Unity project!**_

**Question 2: Build process.**
What build process?  The lesson doesn't mention any build process. Should I build it?  That gives me a Visual Studio solution.  What then?  Deploy to Hololens2?  But the next phrase says press the Play button...?

**Question 3:  Press the Play button.**  
What Play button?  The Play button in the Unity editor?  What was that about the build process then?  If I press Play button in editor I get some error messages in the debugWindow.  How does pressing the play button in Unity involve those multiple users on multiple devices?

**Question 4: Connect your Hololens.**
Connect how?  **Connect** via Holographic Remoting (HR) from within Unity?  The lesson doesn't mention that.  That step is very explicitly covered when required in other tutorials/lessons.  (If I do, 
 and I press Play, Unity crashes as it does most times when trying to HR.)  Or **connect** the Hololens2 via USB and deploy the solution from within Visual Studio?  How does this relate to pressing a play button?  Is the app supposed to create a virtual play button that the user should press?  I didn't see that anywhere.  What about those multiple devices and multiple users?

**Question 5: Any user that joins your Unity project!**
What users?  What project? Multiple users joining my Unity project?  Like a SceneFusion type thing?   What happened to that **application** that was mentioned earlier?  Should it read **application** instead of **project**?  ie Users joining my deployed app on multiple devices?  (What app?  What devices?  See Question 1.  How are these users connected?  What network assumptions?)

I've redone the lesson multiple times in case I'm missing some key step, but no luck so far.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: afd3782f-bda6-fd6a-91d5-f6834d692242
* Version Independent ID: d54407d8-6ec5-51b0-cd7f-e0dcb3888269
* Content: [Multi-user capabilities tutorials - 3. Connecting multiple users - Mixed Reality](https://docs.microsoft.com/en-gb/windows/mixed-reality/mrlearning-sharing(photon)-ch3#feedback)
* Content Source: [mixed-reality-docs/mrlearning-sharing(photon)-ch3.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/mrlearning-sharing(photon)-ch3.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @jessemcculloch
* Microsoft Alias: **jemccull**

**Comment by martinwilter** [comment]
@bblackbourn Sorry for all the issues you experiencing. Unfortunately, there are several flaws in this tutorial series. We are currently working on a major refresh and cleanup of this tutorial series which will bring it to a similar format and flow as the three preceding tutorial series and hopefully resolve all the issues you are facing.

If you can, I recommend waiting for this update as I am confident it will save you a lot of time and also provide a better learning experience.

In the meantime, answers to your questions are provided below.

>The pre-lesson overview reads:
By the end of this lesson, you'll be able to open the application on multiple devices and see the avatar, represented by a sphere for each person that joins.
>
>Question 1: You'll be able to open the Application
What application? Unity (on multiple devices)? A built & deployed solution/application via Unity/VS that has been copied or side-loaded to multiple PCs...or devices? I don't think we create an application by the end of this lesson, just prep really.

It could be any of the following scenarios:
- the deployed app running on multiple HoloLens headsets
- the Unity project running on multiple Unity instances
- or a combination of the above

> The post-lesson summary reads:
Once all the steps above are complete and the build process is also complete, press the Play button and connect your HoloLens 2. You should see a sphere moving around as you move your head. This will be shown for any user that joins your Unity project!

I believe what is meant here is that you deploy the project to your HoloLens headset and run the Unity project and the app on HoloLens simultaneously. Then, when you move your HoloLens headset around, you will see the sphere representing the HoloLens user move in the Unity project.

If you run the app on additional HoloLens headsets, you will see the spheres representing these HoloLens users move in the Unity project as well.

> Question 2: Build process.
What build process? The lesson doesn't mention any build process. Should I build it? That gives me a Visual Studio solution. What then? Deploy to Hololens2? But the next phrase says press the Play button...?

Yes, build and deploy the project to HoloLens. 

> Question 3: Press the Play button.
What Play button? The Play button in the Unity editor? What was that about the build process then? If I press Play button in editor I get some error messages in the debugWindow. How does pressing the play button in Unity involve those multiple users on multiple devices?

Yes, the Play button in Unity.

What errors do you receive in the debug window?

>Question 4: Connect your Hololens.
Connect how? Connect via Holographic Remoting (HR) from within Unity? The lesson doesn't mention that. That step is very explicitly covered when required in other tutorials/lessons. (If I do,
and I press Play, Unity crashes as it does most times when trying to HR.) Or connect the Hololens2 via USB and deploy the solution from within Visual Studio? How does this relate to pressing a play button? Is the app supposed to create a virtual play button that the user should press? I didn't see that anywhere. What about those multiple devices and multiple users?

After you have deployed the project to your HoloLens headset, there's no need to "connect your HoloLens 2", nor to leave it connected.

> Question 5: Any user that joins your Unity project!
What users? What project? Multiple users joining my Unity project? Like a SceneFusion type thing? What happened to that application that was mentioned earlier? Should it read application instead of project? ie Users joining my deployed app on multiple devices? (What app? What devices? See Question 1. How are these users connected? What network assumptions?)

What is meant here is any user who runs the app or Unity project (using the same PUN app ID).

--

Note that currently you will not be able to see the HoloLens users' spheres move because PhotonRoom.cs sets the sphere as a child of the camera, but then GenericNetSync.cs shares the user's local position instead of the camera's position. To quickly fix this, you can try to remove the camera parenting in PhotonRoom.cs by commenting out the following line:

```c#
    void CreatPlayer()
    {
        GameObject player = PhotonNetwork.Instantiate(Path.Combine("Prefabs", "PhotonUser"), Vector3.zero, Quaternion.identity);
        //player.transform.parent = Camera.main.transform;
    }
```

**Comment by bblackbourn** [comment]
Thanks for the excellent and detailed email Martin – much appreciated.

Things make more sense now thanks to your substantial efforts of explanation.  

But, yes, agree 100% that I would never have figured out all that myself from the existing text...and should wait for the shiny new tutorial.

I’ll move on to Spatial Audio series with fingers crossed. 😉

Stay safe.

Cheers
Brad

Sent from Mail for Windows 10

**Comment by martinwilter** [comment]
@bblackbourn You are very welcome, glad to hear it was helpful.

**Comment by mr0ng** [comment]
@bblackbourn the new tutorial series have been updated, feel free to check them out

**Comment by bblackbourn** [comment]
Nice one Sean.  Seems much cleaner & clearer reading through it.  👍
B

Sent from Mail for Windows 10
