### ISSUE TITLE
MRTK - Initializing Project tutorial page should list "Enable Virtual Reality Support" (legacyXR) step

### ISSUE THREAD

**Issue by paco-ms** [MicrosoftDocs/mixed-reality#217]
Using Unity 2019.4.21f11

In the Step "Select Depth Format: 16-bit" - I believe this needs to be preceded by a "Enable the "Virtual Reality Supported" checkbox" step (legacy XR), which is disabled by default, afaics, in Unity 2019 LTS

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24d36428-004c-e29f-ac5a-602bcbabdb25
* Version Independent ID: 01015fb5-d01b-c738-6671-9a0ca9af000e
* Content: [Initializing your project and deploying your first application - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/tutorials/mr-learning-base-02)
* Content Source: [mixed-reality-docs/mr-dev-docs/develop/unity/tutorials/mr-learning-base-02.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-dev-docs/develop/unity/tutorials/mr-learning-base-02.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @jessemcculloch
* Microsoft Alias: **jemccull**

**Comment by veeruby-developer** [comment]
@paco-ms  Thanks for the feedback.
It has been mentioned to enable "Enable the "Virtual Reality Supported" before the step "Select Depth Format: 16-bit" in the tutorial. Please refer to the below screenshot.
![image](https://user-images.githubusercontent.com/61759322/109451220-f4643380-7a72-11eb-93d4-d77f3af9184c.png)

Please let us know if there is anything missing so that we could update.

**Comment by paco-ms** [comment]
You are totally right, I missed it (and I had double checked before posting). Thanks.
