### ISSUE TITLE
HoloLens 2 File Explorer

### ISSUE THREAD

**Issue by NLR-L** [MicrosoftDocs/mixed-reality#2256]
The documentation states that you can "Use the file explorer to browse, upload, and download files. You can work with files in the Documents folder, Pictures folder, and in the local storage folders for apps that you deployed from Visual Studio or the Device Portal."

While for me it's impossible to upload files to the HL2 as it was in the HL1 as can be seen on the image attached below.

![image](https://user-images.githubusercontent.com/44224883/83643974-059a1580-a5b1-11ea-8768-5b2266de5283.png)

On the HL1 I was able to use this, to upload files to the application's [persistent data folder](http://www.appzinside.com/2018/08/06/hololens-and-unity-tip-004-storing-and-retrieving-data-on-hololens-device-storage/).

I would like to be able to upload files again in the file explorer.

HL2 Specs:
Windows version: 19041.1103.arm64fre.vb_release_svc_sydney_rel_prod.200423-1547

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37e0e5f1-b23b-4909-c1ba-6dba39174d30
* Version Independent ID: b0a8777f-e04e-b645-d983-0acb94268f4c
* Content: [Using the Windows Device Portal - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/using-the-windows-device-portal)
* Content Source: [mixed-reality-docs/using-the-windows-device-portal.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/using-the-windows-device-portal.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @JonMLyons
* Microsoft Alias: **jlyons**

**Comment by hamalawi** [comment]
Hi, could you please try scrolling down to the end of the page? That scroll bar on the right shows there might be still content bellow.
If that doesn't work can you please clean your browser's cache and try again.

Thanks

**Comment by Lansenou** [comment]
I've cleared my browsers their caches. The problem still occurs in all the browsers.

(The scroll bar only appeared because I moved the window from a bigger screen to a smaller screen.)

Chrome:
![image](https://user-images.githubusercontent.com/6860432/83727414-50fe0380-a645-11ea-97d4-4704d43bd168.png)

Edge
![image](https://user-images.githubusercontent.com/6860432/83727719-cf5aa580-a645-11ea-9177-6526f32cf4b4.png)


Firefox
![image](https://user-images.githubusercontent.com/6860432/83727535-84d92900-a645-11ea-989f-46349e38fb19.png)

On Firefox my console outputs the following errors:
![image](https://user-images.githubusercontent.com/6860432/83727910-1183e700-a646-11ea-96c4-788c55287a67.png)

settings.json
![image](https://user-images.githubusercontent.com/6860432/83728305-92db7980-a646-11ea-87cd-10703865a904.png)

workspace.json
![image](https://user-images.githubusercontent.com/6860432/83728439-abe42a80-a646-11ea-9bd5-4b2f15dde8b2.png)



And on edge these are the errors:
![image](https://user-images.githubusercontent.com/6860432/83727937-1e083f80-a646-11ea-9c58-cf44927a1d15.png)

**Comment by hamalawi** [comment]
You can't upload to the root folder, please try the Documents folder for example and it should work.

Thanks

**Comment by Lansenou** [comment]
Ah my bad, you're right. Whenever I go into a folder the upload appears, after I scroll down. 🥴
Thanks for your help :)
