### ISSUE TITLE
Cortana no longer used for voice commands for HoloLens 2

### ISSUE THREAD

**Issue by dudziakl** [MicrosoftDocs/mixed-reality#2261]
Please update Voice Commands documentation that "Cortana" prefix is no longer needed for HoloLens 2. Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3659d52-b481-f97b-9824-58874adc0763
* Version Independent ID: b5f1e3d5-cb2d-445b-a737-38498f7863e5
* Content: [Voice input - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/voice-input)
* Content Source: [mixed-reality-docs/voice-input.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/voice-input.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @Hak0n
* Microsoft Alias: **hakons**

**Comment by evmill** [comment]
https://docs.microsoft.com/hololens/hololens-release-notes#known-issues
"We're investigating an issue that requires you to launch the Cortana app after booting the device in order to use the "Hey Cortana" voice activation, and if you updated from a 18362 build, you may see a second app tile for the previous version of the Cortana app in Start that no longer works."

https://docs.microsoft.com/hololens/hololens-release-notes#cortana-updates
"On HoloLens 2, Cortana will no longer support certain device-specific commands like adjusting the volume or restarting the device, which are now supported with the new system voice commands mentioned above. Learn more about the new Cortana app and its direction on our blog here."
https://blogs.windows.com/windowsexperience/2020/02/28/cortana-in-the-upcoming-windows-10-release-focused-on-your-productivity-with-enhanced-security-and-privacy/
