### ISSUE TITLE
NullReference Exception when trying to apply "Mixed Reality / OpenXR / Apply Recommended settings for Hololens 2"

### ISSUE THREAD

**Issue by skons35** [MicrosoftDocs/mixed-reality#238]
Following step by step this OpenXR activation for Hololens 2 project, there is a 
"NullReferenceException: Object reference not set to an instance of an object
Microsoft.MixedReality.OpenXR.Editor.UpdateSettings.ApplyOpenXRSettings () (at Library/PackageCache/com.microsoft.mixedreality.openxr@36a5beedbb7b-1615820934411/Editor/UpdateSettings.cs:46)"
occuring when reaching the project tuning recommendation, located BEFORE the step asking to install ARFoundation package.

I'm with Unity 2020.2f1, OpenXR Plugin 1.0.2, on a fresh created Unity 3D project, tuned by the MS tool "Microsoft Mixed Reality Feature Tool", where i selected Platform Support item : "Mixed Reality OpenXR Plugin 0.1.4 to be applied to that Unity project. (UWP switch done).

Could you check the steps and/or fix that exception ? Thanks in advance.

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 5540ab84-4833-6065-e92b-3eb21f521996
* Version Independent ID: b372839e-13ee-a77b-79c4-49075e74887c
* Content: [Utilisation du plug-in OpenXR de la réalité mixte pour Unity - Mixed Reality](https://docs.microsoft.com/fr-fr/windows/mixed-reality/develop/unity/openxr-getting-started)
* Content Source: [mixed-reality-docs/mr-dev-docs/develop/unity/openxr-getting-started.md](https://github.com/MicrosoftDocs/mixed-reality-pr.fr-fr/blob/live/mixed-reality-docs/mr-dev-docs/develop/unity/openxr-getting-started.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @hferrone
* Microsoft Alias: **alexturn**

**Comment by yl-msft** [comment]
@skons35 
Thanks for the report.  The error might happen when the Unity project didn't setup for OpenXR in XR plugin manager yet.  Please follow this step first before using this menu item.

https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/openxr-getting-started#configuring-xr-plugin-management-for-openxr
![image](https://user-images.githubusercontent.com/33265158/111425900-0a980380-86b1-11eb-98c2-2853a7ea57c0.png)



We think this is indeed a usability problem.  We will customize the error message in Unity console so that you can diagnose this easier.

let us know if above fixed your problem.  Thanks.

**Comment by skons35** [comment]
Hello,
Thanks for the quick reply.

Following your link,  i started again -from scratch- and create a new project, switching to UWP,  adding OpenXR and fixing XR plugin settings as explained (Fix All), then i close the Unity editor, and reopen that project in Unity ( there was a request to activate the new Unity input system in the player settings that is not mentionned in the guide).

Arrived back at the optimization step :   i then reproduced the exception by applying the indicated Mixed Reality / OpenXR / Apply recommended settings for Hololens 2.
It seems easy to reproduce the error in fact, but not sure of the effect of this error on my small project if i try to deploy it anyway on Hololens 2.

I hardly manage to get a recompiled OpenXR sample app running visually fine on the Hololens 2. Has someone recently try the whole steps and get it running fine on up to date Hololens 2  ?

Thanks. 
 

Le 17 mars 2021 07:41:39 GMT+01:00, yl-msft ***@***.***> a écrit :
***@***.***

**Comment by yl-msft** [comment]
@skons35 , did you also checked the "openxr" plugin for the "standalone" build target?  since that setting is used by "unity editor" itself, which is a openxr win32 app itself, we also have logics to modify its settings.  Can you try this out?
![image](https://user-images.githubusercontent.com/33265158/111542796-6d2fe480-872f-11eb-944e-46b31aa873b3.png)

**Comment by hferrone** [comment]
@skons35 Did the above resolve your issue?

**Comment by skons35** [comment]
> 
> 
> @skons35 Did the above resolve your issue?

Hello,
Yes, sorry it take me some time to go back to my tests.
This solves my issue, thanks.
