### ISSUE TITLE
graphics are unreadable in dark mode

### ISSUE THREAD

**Issue by ericleigh007** [MicrosoftDocs/mixed-reality#265]
Sorry to be the bringer of bad news, but the graphics are too dark in dark mode.  The contrast is very low, even for people with normal vision.
-thanks
-e

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 328f3f5f-818a-7148-2f4b-b2a03b120d1b
* Version Independent ID: 0edb668e-6030-b2f2-94e5-facc8364df7e
* Content: [Mixed Reality Partner Program - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/mixed-reality-partner-program#minimum-application-requirements)
* Content Source: [mixed-reality-docs/mixed-reality-partner-program.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/mixed-reality-partner-program.md)
* Service: **unspecified**
* GitHub Login: @cjdgit
* Microsoft Alias: **crderr**

**Comment by mattzmsft** [comment]
@ericleigh007 Good catch! Thanks for flagging that for us. Those particular .PNGs had transparent backgrounds (which I didn't realize). Didn't affect the old site since there was no 'dark mode,' but definitely impacts it here. I re-uploaded those images with a white background, so they'll be legible in 'dark mode' now!
