### ISSUE TITLE
Incorrect shader perf analysis

### ISSUE THREAD

**Issue by dbastien** [MicrosoftDocs/mixed-reality#286]
[Enter feedback here]
For shader performance relative to Unity's standard shader:

Unity's compile and show code only shows you the number of shader instructions in DXIL, not final assembly.

A simple atan call which is a single line in DXIL can expand out to dozens of lines depending on the instruction set of the GPU/Driver, so using just DXIL you can be off by up to an order of magnitude.

You would need to use a tool like pyramid to do a more precise analysis if you want raw instruction count.
Another option is to do an apples to apples comparing in time rendering a frame between the two shaders.
Ideally with full screen objects (not simple quads however as you wouldn't end up with a realistic vertex:pixel ration) with many layers of overdraw to minimize the impact of other aspect of rendering on the final results.

The key takeaway here is that the compilation chain goes like this: HLSL (high level shader language) -> DXIL (directX intermediary language) -> GPU instruction set.

DXIL is very similar to HLSL and not code that actually executes, and does not provide an adequate basis for performance comparison unless in cases where you are modifying an existing shader and know what the operations you are utilizing bake out into as far as code on an average GPU.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28dc995e-2352-2ebd-8aa6-da2a102a5d18
* Version Independent ID: 890774a7-5b95-b43c-9c1f-9eea9fbd075f
* Content: [MRTKStandardShader](https://docs.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/features/rendering/mrtk-standard-shader)
* Content Source: [mrtk-unity/features/rendering/mrtk-standard-shader.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mrtk-unity/features/rendering/mrtk-standard-shader.md)
* Product: **mixed-reality**
* GitHub Login: @CDiaz-MS
* Microsoft Alias: **cadia**

**Comment by polar-kev** [comment]
@Cameron-Micka, would love your input here.

**Comment by Cameron-Micka** [comment]
Hey @dbastien thank you for this feedback! You are totally correct, the shader compiler stats you see in the docs are not 100% representative of the hardware independent, and later hardware dependent, generated assembly. They serve mostly as a high level overview of complexity (similar to the instruction count [D3D11 can provide](https://docs.microsoft.com/en-us/windows/win32/api/d3d11shader/ns-d3d11shader-d3d11_shader_desc)).

I love your idea of creating a non-trivial test scene to compare the shader and then sample the rendering time in a profiler. I'm not familiar with Pyramid? I've only used Pix, Window Performance Analyzer, and RenderDoc (just to get a better look at the actual render state).

As I type this all out it would be probably best if we put these profiling strategies in our docs so that develops could profile for themselves and draw their own conclusions. Especially since we not support so many platforms (UWP, Android, iOS, etc.) and headsets. Would love to hear if you have any more suggestions!

**Comment by dbastien** [comment]
Hello!  Pyramid is an offline shader compilation tool - it goes the full path from HLSL->DXIL->ASIC specific.
With that you can model how many instructions the shader would break down into on a specific GPU family.
It doesn't tell you how many cycles an instruction takes or anything like that, but it is an order of magnitude better for estimating perf.
There might be an improved derivative work but this is the original: https://github.com/jbarczak/Pyramid

The test scene you make could be run on various devices as well if you have an automated test system that measures perf on different platforms already or are planning to create one.
