### ISSUE TITLE
Distortion Error paragraph unclear

### ISSUE THREAD

**Issue by nuernber** [MicrosoftDocs/mixed-reality#293]
The paragraph at https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/locatable-camera.md#distortion-error is a bit unclear to me. It says that the video and still images have been undistorted already. But it also says that that undistortion may have an error of up to 10px. So is this basically saying that the undistortion is imperfect and that essentially the projection matrix in the frame metadata is useless for applications that require precisely undistorted images? 

If the undistortion is imperfect there should be an explanation why this is the case. Is it simply due to inaccuracies in an autocalibration process done for mixed-reality devices before shipping them? 10px sounds like a lot of error that suggests a non-ideal calibration process or a bug in the undistortion function.

**Comment by mattzmsft** [comment]
Thanks @nuernber. I'm looking into this and we'll update the article with more clarity!

**Comment by mattzmsft** [comment]
In digging around with the team, it looks like this documentation got a bit stale, because there's now a more accurate way to do this. I'm going to find someone on the team who can document the better approach, but if you're interested, it's by using the [MediaFrameReader](https://docs.microsoft.com/en-us/uwp/api/windows.media.capture.frames.mediaframereader) runtime class. 

From one of our engineers: "Through this method, you can have extrinsic ([MediaFrameReference.CoordinateSystem](https://docs.microsoft.com/en-us/uwp/api/windows.media.capture.frames.mediaframereference.coordinatesystem#Windows_Media_Capture_Frames_MediaFrameReference_CoordinateSystem)) and intrinsics ([VideoMediaFrame.CameraIntrinsics](https://docs.microsoft.com/en-us/uwp/api/windows.media.capture.frames.videomediaframe.cameraintrinsics#Windows_Media_Capture_Frames_VideoMediaFrame_CameraIntrinsics)) which is accurate and has all calibration information and methods to project/unproject pixels."

**Comment by nuernber** [comment]
Thanks, @mattzmsft for the quick response! Do you know if there are any code examples that use this approach?

Also, I just noticed that https://docs.microsoft.com/en-us/uwp/api/windows.media.devices.core.cameraintrinsics.radialdistortion#Windows_Media_Devices_Core_CameraIntrinsics_RadialDistortion does not give the radial distortion model used when applying these radial distortion coefficients (similarly for tangential distortion). Is this simply using the common Caltech/Matlab model?

**Comment by jessemcculloch** [comment]
Checking to see if this issue can be closed

**Comment by nuernber** [comment]
I still have not recieved answers to my original question and my follow up question. This is still a pertinent issue for myself and others, as I've noticed several people on the HoloLens slack community talking about using the RGB camera for doing what the documentation calls "aligning holograms to real world posters/markers."

**Comment by jessemcculloch** [comment]
Ok, i'll keep it open and see if we can get some better direction on this.  Thanks for the quick response @nuernber

**Comment by cdedmonds** [comment]
@nuernber the 10px error is a limitation of the undistortion hardware block on the original HoloLens.  HoloLens 2 has more accurate undistortion implementation.

**Comment by nuernber** [comment]
Thanks, @cdedmonds for the response. So it's basically a hardware block limitation on HoloLens 1 that doesn't allow for extremely accurate undistortion in hardware, and it's not a bug nor non-optimal camera calibration. That makes sense I guess.

Is there any documentation for how to undistort the preview stream frames? Looks like https://docs.microsoft.com/en-us/uwp/api/windows.media.devices.core.cameraintrinsics shows how to undistort individual points but not the entire frame.

**Comment by jessemcculloch** [comment]
Resolved with #1523
