### ISSUE TITLE
OpenXR Windows Mixed Reality Runtime Controllers Being Unnecessarily Smoothed

### ISSUE THREAD

**Issue by RealSupremium** [MicrosoftDocs/mixed-reality#347]
The hand tracking joint points do not lag behind, but the controller pose is lagging.
This makes fast paced movements tracked on the controller really hard.
It started happening around when the 106.2105.21002 was released. This was in the developer preview too.
I hope the OpenXR team sees this.

Thanks.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9b0b469b-075e-0476-4d19-103c4bea67f0
* Version Independent ID: 2a82b90e-24c0-d186-1e85-5d725c1748db
* Content: [OpenXR troubleshooting - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/native/openxr-troubleshooting)
* Content Source: [mixed-reality-docs/mr-dev-docs/develop/native/openxr-troubleshooting.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-dev-docs/develop/native/openxr-troubleshooting.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @thetuvix
* Microsoft Alias: **alexturn**

**Comment by yl-msft** [comment]
@RealSupremium   Thanks for reporting the issue here.  You have a very good eye on the latency for inputs.  The dev team is looking into this issue, and acknowledged the issue.  We will release the fix as soon as the team can, and I will ping back here when the fix is released.  Thanks and please keep us updated on any issues you encountered and like us to pay attention to.
