### ISSUE TITLE
Hololens 2 & Leap Motion

### ISSUE THREAD

**Issue by CYChuang** [MicrosoftDocs/mixed-reality#363]
Hello, I have some problems and I hope someone can help me.
I use Unity to develop Hololens 2's application, and I use Leap Motion to get my hand in another sight.
When I work in the Unity environment, I can catch my hand by Leap Motion.
However, I can't build the UWP application and Unity will show the error like this: [https://imgur.com/TKJF7Rm](https://imgur.com/TKJF7Rm) 
So I want to know:
1. Can Leap Motion works when it connect Hololens 2?
2. How should I solve the error in the Unity?
3. Can Leap Motion works in the UWP application? and How?

**Comment by CDiaz-MS** [comment]
Hello @CYChuang,

Thank you for the questions.  

1. Currently, MRTK's leap motion provider is supported on the Standalone platform while in the editor and in a build.  However, while on the UWP platform, the leap provider is only supported in editor and not in a build.  This is noted under the top gif in the [Leap Motion MRTK docs](https://docs.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/supported-devices/leap-motion-mrtk?view=mrtkunity-2021-05)
2. The fix for the issue is in progress in the main MRTK repo

**Comment by CYChuang** [comment]
@CDiaz-MS Thanks for your answer and I hope the problem will soon be fix.
