### ISSUE TITLE
Visual studio doesn't show an automatic popup for remote machine information

### ISSUE THREAD

**Issue by julesra** [MicrosoftDocs/mixed-reality#381]
This article says that deploying to Remote Machine in C# would pop up a window asking for the IP address, but my Visual Studio just gave me this error instead of popping up a window (error below).

If this happens to all recent VS versions, I suggest the documentation should suggest that the user type the IP address under project Properties -> Debugging -> Machine Name, instead of waiting for the popup as currently suggested.

My version of VS is Community 2019 v16.9.1

```
3>------ Deploy started: Project: MRTKTestHLD6, Configuration: Release ARM64 ------
3>Error: Microsoft Visual Studio Remote Debugging Monitor cannot start without a Machine Name. Open project properties and specify a Machine Name under 'Configuration Properties -> Debugging'
========== Build: 2 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c174da8-1ca1-0f79-9df0-608f12b041a4
* Version Independent ID: b58f67c4-dba3-b892-b97b-3ed667a19f6a
* Content: [Using Visual Studio to deploy and debug - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/platform-capabilities-and-apis/using-visual-studio?tabs=hl2)
* Content Source: [mixed-reality-docs/mr-dev-docs/develop/platform-capabilities-and-apis/using-visual-studio.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-dev-docs/develop/platform-capabilities-and-apis/using-visual-studio.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @pbarnettms
* Microsoft Alias: **pbarnett**

**Comment by pbarnettms** [comment]
Are you certain that your project is C#?  Unity uses il2cpp now which produces a C++ project.  The proposed documentation change is incorrect for C# projects, and the error message you list below is also consistent with C++ projects.  I would also not expect a C# project to have a ‘Release ARM64’ configuration, unless you manually created one.

From: julesra ***@***.***>
Sent: Monday, July 19, 2021 10:26 AM
To: MicrosoftDocs/mixed-reality ***@***.***>
Cc: Paul Barnett ***@***.***>; Mention ***@***.***>
Subject: [MicrosoftDocs/mixed-reality] Visual studio doesn't show an automatic popup for remote machine information (#381)


This article says that deploying to Remote Machine in C# would pop up a window asking for the IP address, but my Visual Studio just gave me this error instead of popping up a window (error below).

If this happens to all recent VS versions, I suggest the documentation should suggest that the user type the IP address under project Properties -> Debugging -> Machine Name, instead of waiting for the popup as currently suggested.

My version of VS is Community 2019 v16.9.1

3>------ Deploy started: Project: MRTKTestHLD6, Configuration: Release ARM64 ------



3>Error: Microsoft Visual Studio Remote Debugging Monitor cannot start without a Machine Name. Open project properties and specify a Machine Name under 'Configuration Properties -> Debugging'



========== Build: 2 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========



________________________________
Document Details

⚠ Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.

  *   ID: 1c174da8-1ca1-0f79-9df0-608f12b041a4
  *   Version Independent ID: b58f67c4-dba3-b892-b97b-3ed667a19f6a
  *   Content: Using Visual Studio to deploy and debug - Mixed Reality<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fwindows%2Fmixed-reality%2Fdevelop%2Fplatform-capabilities-and-apis%2Fusing-visual-studio%3Ftabs%3Dhl2&data=04%7C01%7CPaul.Barnett%40microsoft.com%7Cf7e6792e1b6e4db488c308d94ada478d%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637623123643276355%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=x950JN4ayjkL%2FuoLMHM2OJVVPOliYiVwXraNq7XM%2F6Q%3D&reserved=0>
  *   Content Source: mixed-reality-docs/mr-dev-docs/develop/platform-capabilities-and-apis/using-visual-studio.md<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2Fmixed-reality%2Fblob%2Fdocs%2Fmixed-reality-docs%2Fmr-dev-docs%2Fdevelop%2Fplatform-capabilities-and-apis%2Fusing-visual-studio.md&data=04%7C01%7CPaul.Barnett%40microsoft.com%7Cf7e6792e1b6e4db488c308d94ada478d%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637623123643286352%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=irNNW4B%2FPheqDB92CObuxIz00rZSkUkH7VKkWSVfBuA%3D&reserved=0>
  *   Product: mixed-reality
  *   Technology: mr-dev
  *   GitHub Login: @pbarnettms<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fpbarnettms&data=04%7C01%7CPaul.Barnett%40microsoft.com%7Cf7e6792e1b6e4db488c308d94ada478d%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637623123643286352%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=3r68pWxhm2ELFrPMQ5FwytNIf%2FJM9W24ByrzFg%2BDQaM%3D&reserved=0>
  *   Microsoft Alias: pbarnett

**Comment by julesra** [comment]
Hi sorry my bad, I am building a Unity3D C# project but it is being built as a VS C++ project, I didn't realize this. My change doesn't apply for C# in this case, it can be discarded. Sorry the confusion.
