### ISSUE TITLE
Min Target: 10240

### ISSUE THREAD

**Issue by jfoshee** [MicrosoftDocs/mixed-reality#432]
The Hololens Emulator will not be listed as a debug/deploy target if you set the Target Min Version above **Windows 10 (10.0; Build 10240)**.  It is frustrating when features are hidden and no reason is shown.  

Thanks to this thread for the info: https://forums.hololens.com/discussion/292/hololens-emulator-not-appearing-as-a-debug-target

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0051f2fd-9bcd-7eb8-48f0-b8b170d42a49
* Version Independent ID: 2c1a0a2b-6a3f-1a1d-caf1-4a06caf5411b
* Content: [Using the HoloLens emulator - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/using-the-hololens-emulator)
* Content Source: [mixed-reality-docs/using-the-hololens-emulator.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/using-the-hololens-emulator.md)
* Service: **unspecified**
* Product: **windows**
* GitHub Login: @JonMLyons
* Microsoft Alias: **jlyons**

**Comment by mattzmsft** [comment]
@jfoshee thanks for flagging this! I'm looking into it with the emulator lead to understand why this is and if it's intentional.

**Comment by mattzmsft** [comment]
In chatting with @JonMLyons, this is an expected behavior (though we understand why it's frustrating). We're passing that feedback along to the Visual Studio team.

**Comment by mattzmsft** [comment]
By the way, just wanted to add this follow-up: it seems like it's an intentional choice by the Visual Studio team to hide emulator targets that don't match the project's UWP version (vs. showing them, but having them disabled or something like that). The VS team said the best way to tell them that this isn't desirable is to report it as an issue at [this site](https://developercommunity.visualstudio.com/spaces/8/index.html), and then get it upvoted. They need to see how many customers agree with your frustration and would want it changed. We still passed along the feedback internally, but loud customer voice is the best way to enact change!
