### ISSUE TITLE
hp reverb g2 with amd gpu error 13-14 fix

### ISSUE THREAD

**Issue by cousinben6** [MicrosoftDocs/mixed-reality#463]
Working around Error 13-14 for amd gpu's

AMD GPU's normally have a maximum data output, and if you are running 2 monitors with 1 being 144hz, or 2 monitors with 1 being 2/3/4k, 90hz full resolution on your hp reverb g2 reads error 13-14

To fix it lower the resolution or refresh rate of your hp reverb-g2 or of your monitors.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 96c577f1-090c-caed-e039-20625d17485d
* Version Independent ID: 7d9d3ae8-6945-ddea-ac0e-eae8397ecb25
* Content: [HP Reverb G2 FAQs - Enthusiast Guide](https://docs.microsoft.com/en-us/windows/mixed-reality/enthusiast-guide/reverbg2-faq)
* Content Source: [enthusiast-guide/reverbG2-faq.yml](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/enthusiast-guide/reverbG2-faq.yml)
* Product: **mixed-reality**
* Technology: **enthusiast-guide**
* GitHub Login: @qianwen
* Microsoft Alias: **v-qianwen**

**Comment by TheJokingTeen** [comment]
Issue report and workaround for 13-14 error

Let me start off by saying that if manufacturers like HP and software companies like Microsoft say that a GPU is recommended and/or compatible, it should actually WORK. Microsoft has to fix this if they want to keep their word.

Would like to add that it seems some vendor cards of the RX 580 refuse to run (from my testing) the G1 and G2 at 90Hz at all, regardless of the resolution, refresh rate or amounts of monitors. This may be hard to test but it may be limited to cards with two HDMI and two DP ports but i'm not sure if that narrows it down. It is definitely weird that this only happens on some of the cards, but I guess it depends on how the Hololens driver, Holoshell application, WUDF, Radeon Drivers and the HP Reverb/Other WMR brands Firmware was configured.
A few years ago this issue came in the form of a black screen issue, could it be that the software was updated to recognise this failiure and spit out error 13-14? If this is true, it needs to be adjusted what amount of bandwidth it allows, because currently it is way too strict (640x480@30Hz on monitor doesn't even work)

Note: Windows settings reports the headset to be running at a refresh rate of 90Hz, however due to the way the headset responds to the signal by having a very mild to decently noticable flicker, it's clear it's not running a 60Hz stream through a 90Hz signal but rather running 60Hz plain. Despite that, the display refresh rate that's actually being sent can't be viewed through settings, as Display 5 crashes the settings window. Display 5 is likely referring to the actual displays of the HMD instead of the virtualized ones because the HMD display is listed as a child of the graphics card itself, which is the only one out of all of them running at 60Hz.

Personally, I have found a way around this issue. I need to disconnect the monitor and if "let windows decide" is selected as refresh rate it will allow it to run at 90Hz.

Disconnecting the monitor before output to the HMD has been established may not always launch the Windows Mixed Reality Portal software, in which case a quick replugging and unplugging of the monitor cable can give Windows the hint that there was a display output change, thus launching the software, but not before it detects a monitor, because the cable to the monitor would be disconnected by then. 

Often, however, disconnecting the monitor before output to the HMD has been established causes the software to become unresponsive (while not reporting that it is not responding), in which case restarting WUDFHost.exe or sometimes even explorer.exe (I really don't know why) is required to reinitialize the connection with the HMD. On occasion the software figures out it is having issues and restarts something within the software that reestablishes the connection.

Here are some other posts reporting the issue (note that some of these might have been from before the software was updated to give error 13-14)
(RX 580 user in comments) https://www.reddit.com/r/HPReverb/comments/jz3h4q/reverb_g2_and_radeon_rx_6800/
Look for the comment by Sundance604, their HP headset also has this issue (although it's an older hp model): https://www.reddit.com/r/WindowsMR/comments/m4d1d4/windows_mr_only_working_in_60hz/
Post is about RX 5700XT, comments are about the RX 580: https://www.reddit.com/r/HPReverb/comments/jrheg2/your_headset_failed_to_start_at_90hz_make_sure/
(RX 580 user who managed to fix it by turning off freesync and lowering refresh rate and resolution on monitor) https://www.reddit.com/r/WindowsMR/comments/a8slry/headset_will_only_show_any_display_when_windows/
https://www.reddit.com/r/WindowsMR/comments/di50d9/hp_reverb_locked_to_60hz_60_only/
https://www.reddit.com/r/HPReverb/comments/mg3ly2/new_monitor_your_headset_failed_to_start_at_90hz/
https://www.reddit.com/r/HPReverb/comments/khwnw5/your_headset_failed_to_start_at_90hz_1314_error/
https://www.reddit.com/r/WindowsMR/comments/jfzwyc/error_code_1314/

Other posts without RX 580/480 or without HP headsets:
https://www.reddit.com/r/WindowsMR/comments/oi2wzp/90hz_isnt_working/
https://www.reddit.com/r/WindowsMR/comments/ltreqw/samsung_hmd_odyssey_stuck_at_60hz/
https://www.reddit.com/r/WindowsMR/comments/97d7iv/dell_visor_amd_rx580_ryzen_1700_no_display_at_90hz/
https://www.reddit.com/r/WindowsMR/comments/m4d1d4/windows_mr_only_working_in_60hz/
https://www.reddit.com/r/WindowsMR/comments/lk5k6s/error_1314_with_amd_drivers/

I would be glad to provide diagnostics if someone at MSFT wants to look into this issue.

**Comment by TheJokingTeen** [comment]
@PRMerger13 Please note for many users this has not been fixed. Monitor allocation with WMR has been broken for a while now, WMRP seems not to decrease monitor resolution at launch of WMR. Even if this is done by the user it often does not work until lowering down to a monitor resolution of 800x600 or even 640x480. This gets even worse when considering a user session reload is often needed (or a restart of runtimebroker.exe and/or mixedrealityportal.brokered.exe? (not completely sure if at all)) for the WMR software to realise the available bandwidth to the gpu has been increased (this may be mitigated by using "let windows decide" but is very inconsistent when trying it, sometimes choosing 60hz over 90hz). When booting up WMR after this, your monitor resolution can be scaled up to 1920x1080@60 while when selecting this monitor resolution manually has never allowed me to launch WMR at 90hz.

Please note when testing this, that the issue only occurs on cards like the AMD RX 580 because of limited bandwidth. However, this should still not be happening, and the error code should also disclose the issue better.

**Comment by TheJokingTeen** [comment]
Either the issue magically went away, but it seems Settings no longer crashes when looking at Display info for the HMD. Thanks devs! (plz tell me if this was fixed or whether I should doubt my sanity). Other issues here still remain though. The guide for the workaround to the issue is not that reliable and I've found more reliable methods of achieving 90Hz, although they are still very annoying to use.

**Comment by TheJokingTeen** [comment]
nope still an issue

**Comment by qianw211** [comment]
Please see this docs page: https://learn.microsoft.com/en-us/windows/mixed-reality/enthusiast-guide/error-codes on fix for 13-14 errors. Also, we're updating the Windows Mixed Reality documentation extensively, please check back in the near future for up-to-date content.

**Comment by ErrorRaffyline0** [comment]
lmao i rewrote that part of the documentation to get around the issue
