### ISSUE TITLE
Where is the package EXE I can share?

### ISSUE THREAD

**Issue by ivankio** [MicrosoftDocs/mixed-reality#474]
"Unity's naming conventions may differ from what you're usually used to in Visual Studio"
When talking about developers exploring VR with Unity, I guess it's reasonable to assume a bunch of developers trying to make some sense of UWP are more used to deployment with Unity than Visual Studio.
With this documentation, we manage to painfully get our project out of unity, and get a bunch of meaningless tree lists in VS. What do I do then to get an EXE I can share in a USB stick with other users? We were willing to drop steam in favor of native WMR integration, but this is way too much bureaucracy and low abstraction for the small team. With the extra incompatibilities, bugs and steps, UWP should be warding away a whole bunch of creative content.
The documentation dropping the ball midway and leaving us before the crucial part is really absurd.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 240922bb-42ba-7082-8605-50f40223ce9a
* Version Independent ID: 749d9a63-b1bd-9dce-ca82-32a6fa0006d0
* Content: [Exporting and building a Unity Visual Studio solution - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/exporting-and-building-a-unity-visual-studio-solution)
* Content Source: [mixed-reality-docs/exporting-and-building-a-unity-visual-studio-solution.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/exporting-and-building-a-unity-visual-studio-solution.md)
* Product: **windows**
* GitHub Login: @BrandonBray
* Microsoft Alias: **mazeller**

**Comment by mattzmsft** [comment]
Thanks for the feedback @ivankio. You're the first to mention this specific issue, but I'll try to find an answer for you!

**Comment by ivankio** [comment]
I mean, the docs feel tailored only to programmers with formal education, that already use the same conventions and tools. I miss a comprehensive linear workflow from start to finish. It seems quite straight forward process with few variations, not a blank canvas of deployment. Something more in these lines: https://winplatform.wordpress.com/2017/09/06/creating-3d-icons-for-your-mixed-reality-uwp-app/ where I finally understood how to get a 3d icon for the app. When I tried to understand through official documentation (https://docs.microsoft.com/en-us/windows/mixed-reality/implementing-3d-app-launchers), it says to edit the manifest XML, but being unfamiliar to publishing through VS, the manifest only leads us to a tabbed layout, I'd never guess I had to right click and view source. Assumptions like this is what makes it so confusing. Like it pushes glb as a common format.

Let's say I'm now lost at the certificate part. In the Packaging Apps section, https://docs.microsoft.com/pt-br/windows/uwp/packaging/create-certificate-package-signing is the only page on the topic, but it's about manual packaging outside VS. If we follow the link back to the process inside VS, https://docs.microsoft.com/pt-br/windows/uwp/packaging/packaging-uwp-apps#configure-an-app-package just say we can chose a certificate and the article move on to uploading. Where can I get such certificate? No idea and no direction. Probably buried somewhere on one of my 10+ tabs of the same manual.

I imagine this 3+ days learning curve just to output an Unity project still without confidence and for manual distribution wouldn't be helping more content creators reach the platform. I now have a better idea what may have contributed to that Oculus certification downtime in March and why Unreal Engine still postpone stable support for WMR.

**Comment by mattzmsft** [comment]
I understand what you're saying, and wish there were a simple way to address this, but creating an app from end to end requires a ton of documentation and can't just exist in a single article that addresses everything. Every little change or possible decision requires its own conceptual documentation. I work with a lot of tabs open as well :-) 

For your 3D icon example, we love that the community writes summary guides, but all the content in that article is covered in multiple articles in our documentation (including the [GLB requirement](https://docs.microsoft.com/en-us/windows/mixed-reality/creating-3d-models-for-use-in-the-windows-mixed-reality-home)) because we have to go a lot deeper than the straightforward approach of that blog. That being said, good point about us not specifying the "right click to view source code" thing... you're right that we just missed calling that out!

As for the certificate stuff you're pointing out, I don't have anything to do with the Windows UWP documentation, but I have submitted an app to the Store successfully (and I'm not a trained dev). I think the reason it doesn't specify further steps is because you don't have to do anything. When you're creating a UWP app for the Windows Store, you're automatically given a test certificate. The real certificate is assigned when you go through the Store publishing process, but I don't believe there's any special certificate action you would take. Did you run into an issue? Or are you just saying you didn't know if there was something you were supposed to do that wasn't clear? Because I don't think you have to manually do or "choose" anything there... you just leave it as is.
