### ISSUE TITLE
Download Hololens emulator?

### ISSUE THREAD

**Issue by bjthomson** [MicrosoftDocs/mixed-reality#507]
https://docs.microsoft.com/en-us/windows/mixed-reality/install-the-tools has a link "Get the HoloLens emulator!", to here...https://docs.microsoft.com/en-us/windows/mixed-reality/using-the-hololens-emulator which has a link "Get the HoloLens emulator!" back to this page...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e6144653-f7f3-0ad2-5c8f-24310633144a
* Version Independent ID: a810412b-2ff0-29d3-3004-af58ce8c24be
* Content: [Install the tools - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/install-the-tools)
* Content Source: [mixed-reality-docs/install-the-tools.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/install-the-tools.md)
* Product: **windows**
* GitHub Login: @mattzmsft
* Microsoft Alias: **mazeller**

**Comment by drstark** [comment]
I had the same problem. They tell you what you need to setup the emulator, but they don't tell you where to get it or how to actually install it anywhere. Microsoft still has a long way to go on HoloLens documentation.

**Comment by mattzmsft** [comment]
Hey guys, just want to clarify, the link to download the HoloLens emulator for two different versions of Windows IS on the "Install the tools page" you're referencing. It's in the "Installation checklist for HoloLens" section towards the top of the page. 

![image](https://user-images.githubusercontent.com/33294058/44753859-6dfebd80-aad4-11e8-8982-293fac2b8c3c.png)

What you're clicking on in the intro paragraph is a description of what's on the page. I totally get the confusion that if you click "HoloLens emulator" in that paragraph it takes you to a page about using the HoloLens emulator. But that's because we model the Wikipedia style of cross-linking to articles about other topics if that topic is referenced on a page. I'll incorporate @malanb5's idea to help make this more clear and i'll remove the link from the top of the page so people don't assume that's a download link (it was never meant to be, just an informative cross-link).
