### ISSUE TITLE
Missing info on Dwell page

### ISSUE THREAD

**Issue by sostel** [MicrosoftDocs/mixed-reality#530]
[Enter feedback here]
What happened to Eye Gaze & Dwell? What are recommended dwell times? How do dwell times affect user satisfaction and usability?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 369d5fce-cef9-e946-4c11-e12ef4ef61fe
* Version Independent ID: 5a1c2b5d-20bf-d316-775a-2c6934033174
* Content: [Dwell - Mixed Reality Toolkit](https://docs.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/features/ux-building-blocks/dwell?view=mrtkunity-2021-05)
* Content Source: [mrtk-unity/features/ux-building-blocks/dwell.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mrtk-unity/features/ux-building-blocks/dwell.md)
* Product: **mixed-reality**
* GitHub Login: @cre8ivepark
* Microsoft Alias: **dongpark**

**Comment by cre8ivepark** [comment]
The content in this page is old head-gaze + dwell contributed by D365 team.You can find different Eye-gaze and dwell in the concept Docs page. https://docs.microsoft.com/en-us/windows/mixed-reality/design/gaze-and-dwell-eyes Sent from Mail for Windows From: sostelSent: Wednesday, March 2, 2022 11:58 AMTo: MicrosoftDocs/mixed-realityCc: Yoon Park; MentionSubject: [MicrosoftDocs/mixed-reality] Missing info on Dwell page (Issue #530) [Enter feedback here]What happened to Eye Gaze & Dwell? What are recommended dwell times? How do dwell times affect user satisfaction and usability?Document Details⚠ Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.ID: 369d5fce-cef9-e946-4c11-e12ef4ef61feVersion Independent ID: 5a1c2b5d-20bf-d316-775a-2c6934033174Content: Dwell - Mixed Reality ToolkitContent Source: mrtk-unity/features/ux-building-blocks/dwell.mdProduct: mixed-realityGitHub Login: @cre8iveparkMicrosoft Alias: dongpark—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by typride** [comment]
I believe you're referring to this page? https://docs.microsoft.com/en-us/windows/mixed-reality/design/gaze-and-dwell-eyes

I'll close this for now, as it seems that the topics you're mentioning are mostly covered in that page. Can reopen if this is incorrect! 

Thanks!
