### ISSUE TITLE
Could you please explain better how to access the sensor data from Unity or if it is possible at all. Thank you :)

### ISSUE THREAD

**Issue by maguileracanon** [MicrosoftDocs/mixed-reality#538]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da146661-e620-72d3-95e2-4c0a751245b7
* Version Independent ID: de5c43c1-653b-aa23-948f-108cc63f085e
* Content: [HoloLens Research Mode - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/research-mode)
* Content Source: [mixed-reality-docs/research-mode.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/research-mode.md)
* Product: **windows**
* GitHub Login: @davidgedye
* Microsoft Alias: **dgedye**

**Comment by CaptainTimberTim** [comment]
I figured out how to access the sensor streams through a Uniy app. Helpful was this Blog post: https://mtaulty.com/2018/04/06/experimenting-with-research-mode-and-sensor-streams-on-hololens-redstone-4-preview/
that kindof describes how to use the API (but he does not use Unity). 
The biggest problem was that "Access denied" error he also had and fixed in the post. But his fix didn't work for me.
This Japanese blog post gave me the missing hints (I don't speak japanese, but the files are still english) http://akihiro-document.azurewebsites.net/post/hololens_researchmode2/
In short: you have to add the permission to your Package.appxmanifest file manually, after you build the app in unity . 
 1- xmlns:rescap="http://schemas.microsoft.com/appx/manifest/foundation/windows10/restrictedcapabilities" needs to go in the <Package> tag 
 2- add rescap to the "IgnorableNamespaces" tag also in <Package>
 3- add <rescap:Capability Name="perceptionSensorsExperimental" /> in the <Capabilities> tag listing (important: it should be BEFORE the <DeviceCapability \> entries.

The Git repo of the japanese guy is also helpful to get a first test going: https://github.com/akihiro0105/HoloLensResearchmodeDemo 

Hope that helps those who are as clueless as I was ;)
