### ISSUE TITLE
Holographic Remoting App on the emulator?

### ISSUE THREAD

**Issue by drstark** [MicrosoftDocs/mixed-reality#539]
Is it possible to get the Holographic Remoting Player on the emulator? I can't get it from the Windows Store, and I can't find anywhere to download separately and install through the Device Portal. 

If it's not possible at this time, it should definitely be added in the future. If you're making an app intended to be played through the Holographic Remoting Player, then being able to test in the same environment would be a big help.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0051f2fd-9bcd-7eb8-48f0-b8b170d42a49
* Version Independent ID: 2c1a0a2b-6a3f-1a1d-caf1-4a06caf5411b
* Content: [Using the HoloLens emulator - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/using-the-hololens-emulator)
* Content Source: [mixed-reality-docs/using-the-hololens-emulator.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/using-the-hololens-emulator.md)
* Product: **windows**
* GitHub Login: @JonMLyons
* Microsoft Alias: **jlyons**

**Comment by Holo-Krzysztof** [comment]
It is possible, I've already had it working at some point.
As far as I remember you can just go into the store and download it on the RS4 emulator, no login needed.
With the previous one (RS1 I think) you'd need to go to the emulator settings, check a box so that it asks you for MS account credentials and restart, then you'd have to login after the emulator starts and you should be able to get the remoting app from the store again.

**Comment by pbarnettms** [comment]
The previous comment is accurate.  If you need to get to the Store, you can enable "Sign in with Microsoft Account" on the "Account" tab of the emulator settings (the ">>" button on the toolbar).
