### ISSUE TITLE
Unable to deploy

### ISSUE THREAD

**Issue by medullatheprogrammer** [MicrosoftDocs/mixed-reality#552]
Hi Everyone, 

Sorry for the troubles, but I was wondering if someone would be kind enough to offer some advice. I'm new to HoloLens and just starting this "MR Basics 100: Getting started with Unity". 

I've followed the instructions, but I'm still unable to deploy the app. I'm using a Surface Laptop (and meet all the requirements). I'm using an emulator at this stage and plan to acquire the HoloLens later. 

When I click debug -&gt; start without debugging I get the following error: 

Initially it seems to be working fine. Then I get an error message saying:

"There were deployment errors. Continue?" Yes/No

I click yes and then I get the following message: 
"The project needs to be deployed before it can be started. Verify the project is selected to be deployed in the Solution Configuration Manager, or deploy it explicitly by clicking one of the Deploy commands in the Build menu."

In the error output, I also get 'ApplicationView.SuppressSystemOverlays.set' is obsolete: 'Use the TryEnterFullScreen method and IsFullScreenMode property instead od SuppressSystemOverlays. For more info, see MSDN.'

Any help would be greatly appreciated. I'm using Unity 2017.4.1f1 Personal. 

Many thanks,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8969b329-9061-f1c0-70c7-b99aa0aa1b94
* Version Independent ID: a80974ef-fbc2-7559-7711-b899e349c010
* Content: [MR Basics 100 - Getting started with Unity - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/holograms-100)
* Content Source: [mixed-reality-docs/holograms-100.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/holograms-100.md)
* Product: **windows**
* GitHub Login: @keveleigh
* Microsoft Alias: **kurtie**

**Comment by ShadowsOftheBeast** [comment]
Hi I am getting this same issues, has this been resolved, i am quite suprised that there has not been any update or solutions to this problem. i cant deploy as well getting the same errors as yourself as well as *.pdb files which don't seem to be in the project, but are generated.

**Comment by ShadowsOftheBeast** [comment]
oh i am using unity 2018.3.0f2 and Visual studio 2017 Enterpise

**Comment by keveleigh** [comment]
I'm unable to repro this issue. Following the steps in MR Basics 100, I was successfully able to deploy the cube app to the emulator. Does the [emulator launch for you](https://docs.microsoft.com/en-us/windows/mixed-reality/using-the-hololens-emulator#hololens-emulator-system-requirements)?

![image](https://user-images.githubusercontent.com/3580640/50368024-9013c400-0539-11e9-9d63-64998d7f8ecc.png)

**Comment by ShadowsOftheBeast** [comment]
Hi keveleigh, thanks for your reply no i am trying to deploy to my Hololens headset i am not using an emulator, what seems to be happening now is i use the IL2CPP scripting back end rather than .net, then i create my build with all the settings as instructed in the video, but once i deploy, all i see is a broken app screen from my headset

**Comment by ShadowsOftheBeast** [comment]
here is my build output:
1>ObjectFiles: 537 of which compiled: 0
1>Total compilation time: 5387 milliseconds.
1>Creating library C:\Users\Kingsley MagnusEweka\Documents\Unity Projects\MixedReality\MixedRealityIntro\App\build\obj\il2cppOutputProject\Win32\Release\linkresult_64CA999163C5412E753FE7B616291834\GameAssembly.lib and object C:\Users\Kingsley MagnusEweka\Documents\Unity Projects\MixedReality\MixedRealityIntro\App\build\obj\il2cppOutputProject\Win32\Release\linkresult_64CA999163C5412E753FE7B616291834\GameAssembly.exp
1>Total link time: 24455 milliseconds.
1>Cleaned up 2 object files.
2>------ Build started: Project: MixedRealityIntro, Configuration: Release Win32 ------
2>App.cpp
2>UnityGenerated.cpp
2>c:\users\kingsley magnuseweka\documents\unity projects\mixedreality\mixedrealityintro\app\mixedrealityintro\app.cpp(26): warning C4973: 'Windows::UI::ViewManagement::IApplicationView2::SuppressSystemOverlays::set': marked as deprecated
2>c:\users\kingsley magnuseweka\documents\unity projects\mixedreality\mixedrealityintro\app\mixedrealityintro\app.cpp(26): note: Message: 'Use the TryEnterFullScreen method and IsFullScreenMode property instead of SuppressSystemOverlays. For more info, see MSDN.'
2>Generating code
2>0 of 160 functions ( 0.0%) were compiled, the rest were copied from previous compilation.
2>  0 functions were new in current compilation
2>  0 functions had inline decision re-evaluated but remain unchanged
2>Finished generating code
2>MixedRealityIntro.vcxproj -> C:\Users\Kingsley MagnusEweka\Documents\Unity Projects\MixedReality\MixedRealityIntro\App\build\bin\Win32\Release\MixedRealityIntro.exe
2>GENERATEPROJECTPRIFILE : warning PRI249: 0xdef00520 - Invalid qualifier: DLL-RESOURCES
2>GENERATEPROJECTPRIFILE : warning PRI249: 0xdef00520 - Invalid qualifier: DLL-RESOURCES
2>Done building project "MixedRealityIntro.vcxproj".
3>------ Deploy started: Project: MixedRealityIntro, Configuration: Release Win32 ------
Deploying to Phone Internal Storage...
Creating a new clean layout...
Copying files: Total 64 mb to layout...
Checking whether required frameworks are installed...
Registering the application to run from layout...
Deployment complete (0:00:18.363). Full package name: "Template3D_1.0.0.0_x86__pzq3xp76mxafg"
========== Build: 2 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
========== Deploy: 1 succeeded, 0 failed, 0 skipped ==========

**Comment by ShadowsOftheBeast** [comment]
here is my build settings:
[img]https://www.flickr.com/gp/146001590@N06/8tR4jv[img]

**Comment by ShadowsOftheBeast** [comment]
i tried it again and this is what i get in my hololens.

**Comment by ShadowsOftheBeast** [comment]
Could you please give me your project settings (including the player settings, and the XR settings )and build settings? my other settings in player settings is using the IL2CPP for backend scripting. thank you

**Comment by tghoshmo** [comment]
Under Build Settings, Scenes/SampleScene should be unchecked.

**Comment by lesterkell** [comment]
I have the exact same issue.  I unchecked Scenes/SampleScene but still doesn't solve the issue.  Any more support on this, please?

Thanks

**Comment by hferrone** [comment]
@keveleigh Was this resolved and can it be closed?

**Comment by keveleigh** [comment]
Sometimes when I've gotten into this state, uninstalling the app on the HoloLens device and reinstalling from scratch fixes it.

@hferrone I'm happy to keep helping them debug (though it's been a while now...), but I don't think this needs to be left open as a docs issue.
