### ISSUE TITLE
Project config/legacy XR settings missing explanations

### ISSUE THREAD

**Issue by polar-kev** [MicrosoftDocs/mixed-reality#58]
### Project Configuration Settings are not Explained
This tutorial is geared towards beginners yet does not explain the configuration settings. The user is told to simply check/select settings but is not told why or what these settings do with respect to the project or the hololens 2 device. These config settings include:

- MS HRTF Spatializer
- Depth Format
- Spatial Awareness Layer
- Single Pass instanced render path
- Legacy XR API

Each of them needs an explanation as they will all leave beginners confused as to what they are doing.

### No message about Built-in XR deprecation
Warnings are likely to confuse users who are new to Unity/MR development. The Unity editor provides a warning about built-in XR being deprecated in a future version of Unity. This should be addressed in the tutorial either via a link explaining what's happening next (ie. XR SDK) or through a short summary.

![image](https://user-images.githubusercontent.com/30964480/93829964-bd683700-fc23-11ea-8950-3d1fca24fb53.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24d36428-004c-e29f-ac5a-602bcbabdb25
* Version Independent ID: 01015fb5-d01b-c738-6671-9a0ca9af000e
* Content: [Getting started tutorials - 2. Initializing your project and deploying your first application - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/tutorials/mr-learning-base-02)
* Content Source: [mixed-reality-docs/mr-dev-docs/develop/unity/tutorials/mr-learning-base-02.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-dev-docs/develop/unity/tutorials/mr-learning-base-02.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @jessemcculloch
* Microsoft Alias: **jemccull**

**Comment by hferrone** [comment]
@mr0ng @martinwilter This is listed as completed in the spreadsheet Sean shared but there is nothing here?

**Comment by martinwilter** [comment]
@hferrone, I think I know what spreadsheet you are referring to now, the issues spreadsheet? If so, that spreadsheet lists the state of the issues as they related to us, not as they related to the repo.

'For Review' means we've responded to the issues not that it's resolved in the repo. 'Done' means you have closed the issue. Our internal status for this issue is 'Backlog', meaning we haven't responded to it. I've been told that PRs on the public repo will be closed, so it's a bit problematic to provide updates to these requests for additional information.
