### ISSUE TITLE
How to deal with IL2CPP build with unity 2018

### ISSUE THREAD

**Issue by gwendalbroudinpro** [MicrosoftDocs/mixed-reality#603]
Hello,

On Unity 2018, .NET scripting back end for UWP is deprecated. We now have to use IL2CPP scripting back end.

Because of that, I don't have a way to have IntelliSense and other tooling for UWP C# code (inside UNITY_WSA compilation symbols), since the dll and the compilation symbols are not available in the unity project. Is there a way to generate some kind of "scripting only project" with the proper .sln/csproj/dll files in order to add UWP targeted code more easily ? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f00922d-8f87-0c40-4b9c-9994be4f8f7f
* Version Independent ID: 75796fe2-31b2-734d-101d-9bf235222344
* Content: [Best practices for working with Unity and Visual Studio - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/best-practices-for-working-with-unity-and-visual-studio)
* Content Source: [mixed-reality-docs/best-practices-for-working-with-unity-and-visual-studio.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/best-practices-for-working-with-unity-and-visual-studio.md)
* Product: **windows**
* GitHub Login: @mattzmsft
* Microsoft Alias: **mazeller**

**Comment by yacuzo** [comment]
This is kind of old now, but here probably many who has not converted yet, so here it goes anyway: 

Read https://docs.unity3d.com/Manual/ManagedCodeDebugging.html under 'Debugging in the player'. 

You should get separate projects in the editor-solution (not the UWP solution) that are 'MyCode.Player'. These will have the same code as 'MyCode', with the exception that compilation symbols will be set for Hololens instead of editor.
This is available from 2018.2. 

WARNING: The FPS in IL2CPP debug mode is super-bad. We are talking a second per frame. It may be better to do this against the emulator if possible.

**Comment by gwendalbroudinpro** [comment]
Yes I saw it, thanks !
