### ISSUE TITLE
It's not right

### ISSUE THREAD

**Issue by wukongiii** [MicrosoftDocs/mixed-reality#605]
1) The project I downloaded from https://github.com/Microsoft/MixedRealityToolkit-Unity today 10/8/2018 is not the same version as this article described. At least the part of the project setup, in my downloaded project contains a scene named SpectatorViewExample contains a SpectatorView gameobject which instantiated from same name prefab, a WorldRoot gameobject, and a NetworkManager attaches a SpectatorViewNetworkManager component,  which this article mentioned nothing about it. If I try to drag a SpectatorViewNetworking prefab to my scene as this article says I should do, It rises a lot of errors.
And I followed it to build a x86 openCV, but it doesn't fit UWP, it needs x64 plugins. What should I do?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d7c80c33-09c9-2f47-7486-d6c406a9a1a4
* Version Independent ID: f8ae5662-23e0-141b-efcc-8e5fb3361193
* Content: [SpectatorView (Preview and Pro) - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/spectator-view)
* Content Source: [mixed-reality-docs/spectator-view.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/spectator-view.md)
* Product: **windows**
* GitHub Login: @danielescudero
* Microsoft Alias: **daescu**

**Comment by danielescudero** [comment]
Thanks @wukongiii, I will update this ASAP. Seems to be out of sync.

**Comment by chrisfromwork** [comment]
Hello,

HoloLens uses x86 binaries. Did the vcpkg steps work for you in order to obtain the needed opencv libs/dlls? It may be that you need to change visual studio's configuration manager from ARM/x64 to x86 in order to build a x86 version of SpectatorViewPlugin.dll and pick up the correct opencv dependencies.

The default branch for the mixed reality toolkit no longer directs to the holo toolkit codebase that SpectatorView Preview was originally developed in. We are actively refactoring SpectatorView in feature/spectatorView branches. The old SpectatorView preview code branches can still be found in branches with htk_* prefixes, such as htk_release (https://github.com/Microsoft/MixedRealityToolkit-Unity/tree/htk_release) and htk_development.

Currently, the Microsoft/MixedRealityToolkit repo's master branch contains coded needed to obtain the SpectatorViewPlugin.dll described above/used in htk_* versions of SpectatorView (as of the date this reply was made). Long term code in the feature/spectatorView branch may replace that in master when the SpectatorView refactor is completed. We will work to update the documentation on this page at that time.

**Comment by jessemcculloch** [comment]
Is this still an issue?

**Comment by jessemcculloch** [comment]
This page has been completely redone, closing this issue
