### ISSUE TITLE
Issue with Photon Unity Networking after following Multi-user capabilities tutorial

### ISSUE THREAD

**Issue by seannie2** [MicrosoftDocs/mixed-reality#63]
I have followed the guide in the documentation here:
https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/tutorials/mr-learning-sharing-03
multiple times, making sure I follow the instructions exactly, but no matter what I do, there is always ~114 errors relating to Photon when I try to build the unity project.
The errors are basically variations of as follows:
`Assets\Photon\PhotonChat\Code\ChatAppSettings.cs(17,11): error CS0246: The type or namespace name 'ExitGames' could not be found (are you missing a using directive or an assembly reference?)
Assets\Photon\PhotonChat\Code\ChatClient.cs(1194,46): error CS0246: The type or namespace name 'EventData' could not be found (are you missing a using directive or an assembly reference?)
Assets\Photon\PhotonChat\Code\ChatClient.cs(941,14): error CS0538: 'IPhotonPeerListener' in explicit interface declaration is not an interface
Assets\Photon\PhotonRealtime\Code\ConnectionHandler.cs(20,26): error CS0246: The type or namespace name 'ExitGames' could not be found (are you missing a using directive or an assembly reference?)
UnityEditor.BuildPlayerWindow+BuildMethodException: 114 errors
  at UnityEditor.BuildPlayerWindow+DefaultBuildMethods.BuildPlayer (UnityEditor.BuildPlayerOptions options) [0x002bb] in <8004fcc221b54f98ba547350ea71d812>:0 
  at UnityEditor.BuildPlayerWindow.CallBuildMethods (System.Boolean askForBuildLocation, UnityEditor.BuildOptions defaultBuildOptions) [0x00080] in <8004fcc221b54f98ba547350ea71d812>:0 
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)
`
I've tried in both 2019.4.5f1 & 2019.4.10f1.
I've successfully exported many unity projects to the HoloLens 2 I'm using, but cannot get the multi-user experience to work.

Sorry if this is not enough info to help, feel free to request any other info.
Thanks in advance.

**Comment by hferrone** [comment]
@mr0ng Can you or the team member that overhauled this tutorial assist?

**Comment by martinwilter** [comment]
Hi @seannie2, this issue is caused by a recent update to the PUN 2 asset (Photon). The tutorials were made with PUN v2.18, however, the current version in the Unity Asset store is v2.22 and somewhere between these version it appears PUN's ability to enable the correct libraries for UWP platform has broken.

We've been able to work around this issue by enabling the WSAPlayer platform in the import settings for Assets/**Photon**/**PhotonLibs**/**Photon3Unity3D.dll**. To do this, make the required changes and click the Apply button. 

You can configure the import settings like this:

![image](https://user-images.githubusercontent.com/16746283/94742072-f55d3180-0329-11eb-9d42-0b17a2d76007.png)

or this:

![image](https://user-images.githubusercontent.com/16746283/94742280-4d943380-032a-11eb-95bf-068a7a2a56df.png)

Hope this helps, but if not, let me know and I'll try to assist further.

CC @hferrone
