### ISSUE TITLE
What is DirectionalIndicatorController script for?

### ISSUE THREAD

**Issue by dudziakl** [MicrosoftDocs/mixed-reality#64]
It is not explained in the tutorial what is the reason to use the DirectionalIndicatorController script. This script makes Indicator inactive and if you are unlucky like me you won't see Indicator at all. I thought that solver is not working and then found that it is just disabled. Why? Everything is just fine (and working) without DirectionalIndicatorController script. I suggest to remove it from the tutorial. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a441bd4f-7fb9-780a-696c-6b07fee8c179
* Version Independent ID: 76453e28-721e-92ee-122c-f1f5ca571377
* Content: [Getting started tutorials - 5. Creating dynamic content using Solvers - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/tutorials/mr-learning-base-05)
* Content Source: [mixed-reality-docs/mr-dev-docs/develop/unity/tutorials/mr-learning-base-05.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-dev-docs/develop/unity/tutorials/mr-learning-base-05.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @jessemcculloch
* Microsoft Alias: **jemccull**

**Comment by dudziakl** [comment]
Sorry, I was wrong. DirectionalIndicatorController script is needed two chapters later. Anyway this should be clarified or it shouldn't be attached at this chapter as it is confusing when testing. It could be added at the end of chapter 7 when floating menu is updated, as this is the best moment to test this functionality.

**Comment by hferrone** [comment]
@martinwilter If you agree I can make a quick update?

**Comment by martinwilter** [comment]
Hi @hferrone, I believe we already addressed this and as requested updated md and image files were emailed to you on August 19th instead of PR created.

Here's the particular commit on my fork https://github.com/martinwilter/mixed-reality/commit/d5b332e6830fd5db246b31a9e08e2483de051d1c

I also made some other fixes at that same time which you will find on the same branch https://github.com/martinwilter/mixed-reality/commits/fix/getting-started-tutorials-issues

![image](https://user-images.githubusercontent.com/16746283/94622762-a2bb4100-0267-11eb-8701-6bc3fb6170e7.png)
