### ISSUE TITLE
how to delete the real occlusion

### ISSUE THREAD

**Issue by ZHUYUEHAN1** [MicrosoftDocs/mixed-reality#659]
Hi
You just add the occlusion, but in the real world, after HoloLens scan the wall it will create a new occlusion of the wall, it will block the window and we cannot see the flower. how did you delete the occlusion in front of the flower?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bbcebd15-ddba-cab7-2de7-866ff0306f86
* Version Independent ID: cfae84ad-db8e-2df4-f475-7fd302cceb86
* Content: [Case study - Looking through holes in your reality - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/case-study-looking-through-holes-in-your-reality)
* Content Source: [mixed-reality-docs/case-study-looking-through-holes-in-your-reality.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/case-study-looking-through-holes-in-your-reality.md)
* Product: **mixed-reality**
* GitHub Login: @EricRehmeyer
* Microsoft Alias: **ericrehm**

**Comment by EricRehmeyer** [comment]
Hi - good question. To get the effect to work, your app needs to avoid drawing an occluding material on the detected world mesh. This will work if you're making your own immersive Unity app, or if you use a model viewing app like [3D Viewer Beta](https://www.microsoft.com/store/productId/9NBLGGH5PM4Z) which doesn't render an occluding material on the detected world mesh. If you are attempting to do this trick in the normal mixed-reality system view, it won't work, because that draws an occluding mesh.

If you were developing your own app and wanted to do both the magic hole effect and have an occluding world mesh, you could probably play with the render order of your flower box, and draw extra pixels to the depth buffer in a way that prevents the world mesh from drawing 'behind' it later. Hope this helps.
