### ISSUE TITLE
Two scripts are missing in the Spatial Mapping prefab

### ISSUE THREAD

**Issue by sannyi** [MicrosoftDocs/mixed-reality#687]
Two scripts are missing in the Spatial Mapping prefab. Probably the SM Collider and SM Render. I've added these two components manually, which fixed the crashing of the emulator.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d680e05-a73a-321c-e7c8-8daa0a2c5249
* Version Independent ID: 8ef33125-aa37-cc1a-0264-bba3a12daf5d
* Content: [MR Basics 101E - Complete project with emulator - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/holograms-101e)
* Content Source: [mixed-reality-docs/holograms-101e.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/holograms-101e.md)
* Product: **mixed-reality**
* GitHub Login: @keveleigh
* Microsoft Alias: **kurtie**

**Comment by ottomp24** [comment]
This is a "bug" in later versions of Unity 2018 and above when importing projects with an older version where those 2 classes are not automatically imported. Just go to XR Settings under Player settings and uncheck/check "Virtual Reality Supported". That will re-download the missing classes.

**Comment by zojhanke** [comment]
@sannyi How did you added these components manually?

**Comment by sannyi** [comment]
@zojhanke In the inspector add the SpatialMapping Renderer and Collider just as you would add any other component (of course the corresponds MS need to be somewhere in the project explorer).

**Comment by riebling** [comment]
Grateful the problem is understood, but neither of these solutions are working for me. Would it be possible to explicitly spell out exactly what to do, in tutorial language, rather than assume familiarity with adding Components or the mysteries of code being added to projects when project settings checkboxes get checked? That is, exactly what corresponding MS (what does "MS" refer to?), and exactly what menu path in Add Component to add Renderer and Collider Components?
(uncheck/check "Virtual Reality Supported" didn't help, still get "Missing (Mono Script)" and "The associated script can not be loaded. Please fix any compile errors and assign a valid script" in the Spatial Mapping Prefab Inspector

**Comment by riebling** [comment]
UPDATE: when using Add Component, rather than try Every. Single. Menu. Choice. to search for Spatial Mapping Collider and Renderer, much faster to type 'spatial mapping' into the search box, then voila, there they are! It's things like this that people familiar with Unity take for granted, and people following tutorials possibly using Unity for nearly the first time ... don't naturally know how to do (as in "as you would add any other component" above... you mean, as any person who already knows how to use Unity would ;) )

**Comment by sannyi** [comment]
> 
> 
> UPDATE: when using Add Component, rather than try Every. Single. Menu. Choice. to search for Spatial Mapping Collider and Renderer, much faster to type 'spatial mapping' into the search box, then voila, there they are! It's things like this that people familiar with Unity take for granted, and people following tutorials possibly using Unity for nearly the first time ... don't naturally know how to do (as in "as you would add any other component" above... you mean, as any person who already knows how to use Unity would ;) )

Thanks for the correction. As a newbie or more advanced user, IMO you don't learn because the code is really just given.

**Comment by kotavy** [comment]
As an additional note, it took me flipping the Depth Format of the Windows Mixed Reality SDK for Unity to re-load the assets. Unchecking/checking Virtual Reality Supported wasn't quite enough. After that, the collider and renderer appeared under the main Component tab -> XR. Added them to the SpatialMapping prefab and re-saved it just to be safe.
