### ISSUE TITLE
Where i can access the Acrylic sample scene?

### ISSUE THREAD

**Issue by nongzhang** [MicrosoftDocs/mixed-reality#733]
[Enter feedback here]
In MRTK 3 Project, I cant find Acrylic sample scene.  In github mixed-reality, there is alse no Acrylic sample scene and no AcrylicHelpr.cs
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4764e56b-0fae-3112-8029-d7487172746b
* Version Independent ID: 4764e56b-0fae-3112-8029-d7487172746b
* Content: [Acrylic Sample Scene - MRTK3](https://learn.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/mrtk3-graphicstools/features/samples/acrylic)
* Content Source: [mrtk-unity/mrtk3-graphicstools/features/samples/acrylic.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mrtk-unity/mrtk3-graphicstools/features/samples/acrylic.md)
* Product: **mixed-reality**
* GitHub Login: @Species521
* Microsoft Alias: **wettigmarti**

**Comment by Species521** [comment]
Hey nongzhang.
The Acrylic sample scene, and all other sample scenes, live in the Mixed Reality Graphics Tools repo now. The MRTK has been split up into several packages to tailor it better to the users' needs.
The Graphics Tools are here: https://github.com/microsoft/MixedReality-GraphicsTools-Unity

![image](https://github.com/MicrosoftDocs/mixed-reality/assets/31127009/14e2d283-6e4d-423b-ad35-cf6264bdf741)


In order to make the sample scenes available, please make sure to activate them inside the Unity Editor in the Graphics Tools tab, "Show Samples".

**Comment by nongzhang** [comment]
thanks,i got it!

**Comment by nongzhang** [comment]
thanks,i got it!
