### ISSUE TITLE
Warnings importing holographic remoting package

### ISSUE THREAD

**Issue by polar-kev** [MicrosoftDocs/mixed-reality#74]
Unity 2019.4.10f1
MRTK 2.4

I was still able to complete the tutorial.

![image](https://user-images.githubusercontent.com/30964480/94589201-d54e4500-0239-11eb-8644-b246387bde69.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55bb143d-e40d-4c26-c310-d4f1777009bb
* Version Independent ID: 29327994-e0cc-83d5-025f-ccf5319c38cb
* Content: [PC Holographic Remoting tutorials - 1. Getting started with PC Holographic Remoting - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/tutorials/mr-learning-pc-holographic-remoting-01)
* Content Source: [mixed-reality-docs/mr-dev-docs/develop/unity/tutorials/mr-learning-pc-holographic-remoting-01.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-dev-docs/develop/unity/tutorials/mr-learning-pc-holographic-remoting-01.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @jessemcculloch
* Microsoft Alias: **jemccull**

**Comment by hferrone** [comment]
@polar-kev Does this happen when you import the MRTK.Tutorials.PCHolographicRemoting.unitypackage or at some other stage?

**Comment by martinwilter** [comment]
Hi @hferrone, yes, those five warnings are thrown when importing the tutorial assets. Specifically, they are caused by the glb models located at Assets > MRTK.Tutorials.PCHolographicRemoting > Models:

![image](https://user-images.githubusercontent.com/16746283/94955356-4cd0de00-049f-11eb-83f4-8e60551b44d5.png)

I don't think the issue causing these warnings affects the purpose of this tutorial, so I believe they can be ignored. I also think the warnings will only be shown on first import or after library rebuild.

By the way, I noticed these models are not actively used in the tutorial (only the MarsCuriosityRover model is shown), so we could switch out those five models with models fully supported by MRTK. If we try to find similar models and renamed them to match the current names, we should be able to do it without having to update any tutorial images. Let me know if this is something you want me to look into.
