### ISSUE TITLE
CloudSpatialException

### ISSUE THREAD

**Issue by Cristian-Hanciuc** [MicrosoftDocs/mixed-reality#77]
[Enter feedback here]

This exception is thrown when trying to create a new azure anchor on Hololens2
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97b7f65b-2300-1e88-3072-5ecc28e5a8e5
* Version Independent ID: 2089610b-9581-ea9b-11c5-7be97e53c584
* Content: [Azure Spatial Anchors tutorials - 2. Getting started with Azure Spatial Anchors - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/tutorials/mr-learning-asa-02)
* Content Source: [mixed-reality-docs/mr-dev-docs/develop/unity/tutorials/mr-learning-asa-02.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-dev-docs/develop/unity/tutorials/mr-learning-asa-02.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @jessemcculloch
* Microsoft Alias: **jemccull**

**Comment by hferrone** [comment]
Hi @Cristian-Hanciuc , can you post the full exception log?

**Comment by martinwilter** [comment]
Hi @Cristian-Hanciuc,

Assuming you configured the account id and key correctly in your project and your HoloLens have internet access, this could potentially be caused by some recent changes to Azure Spatial Anchors portal where, unless you created the ASA resource using East US 2 location, you must now also configure the account domain in your project.

In recent ASA SDK versions, this can now be configured in Assets > AzureSpatialAnchors.SDK > Resources > SpatialAnchorConfig, however, this tutorial is using an older ASA SDK version (v2.2.1) where this configuration option is not available. So to verify if this is the issue I think the best option is to [create a new ASA resource](https://docs.microsoft.com/en-us/azure/spatial-anchors/quickstarts/get-started-unity-hololens#create-a-spatial-anchors-resource) using location **East US 2** and then update your project to use that account id and key.

Please give this a try and let me know if it solved the issue. Thanks.

CC @hferrone

**Comment by chwarr** [comment]
After validating, please make sure your code configures your Azure Spatial Anchor's account domain to match what you see in the Azure portal for that account. Please do not rely on an unset domain to mean East US 2.

**Comment by Efaq** [comment]
@chwarr could you please give more details about "make sure your code configures your Azure Spatial Anchor's account domain"? Exactly which part of the code? And how to configure the ASA account domain? I have had a hard time finding documentation about it, and the problem still persists for me.

Thanks!

**Comment by chwarr** [comment]
See if these sections of the documentation help, @Efaq:

* [Unity for HoloLens](https://docs.microsoft.com/en-us/azure/spatial-anchors/quickstarts/get-started-unity-hololens?tabs=azure-portal#configure-the-account-information) (and similarly for Android and)
* [HoloLens  in C++/WinRT](https://docs.microsoft.com/en-us/azure/spatial-anchors/quickstarts/get-started-hololens?tabs=azure-portal#configure-account-identifier-and-key)
* [Android in Java](https://docs.microsoft.com/en-us/azure/spatial-anchors/quickstarts/get-started-android?tabs=azure-portal%2Copenproject-java#configure-account-identifier-and-key)
* [iOS in Objective-C/Swift](https://docs.microsoft.com/en-us/azure/spatial-anchors/quickstarts/get-started-ios?tabs=azure-portal%2Copenproject-swift#configure-account-identifier-and-key)
* [Xamirin for Android](https://docs.microsoft.com/en-us/azure/spatial-anchors/quickstarts/get-started-xamarin-android?tabs=azure-portal%2Cdeploy-windows#configure-account-identifier-and-key) (and similarly for iOS)

If none of these work, can you open a new issue with the details of what you're encountering?
