### ISSUE TITLE
Missing Step - Need to Set Buttons Y Position to -0.1

### ISSUE THREAD

**Issue by hwinstonuconn** [MicrosoftDocs/mixed-reality#80]
The figure for this tutorial shows the buttons object at Y = -0.1 but this prefab's default
is y = 0.45. Is there a missing step in the instructions? I set Y = -0.1 to make the scene 
consistent with the figures.

Thank you.

Howard

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 19d6068a-8891-8072-20f4-e162462140b9
* Version Independent ID: 8bbeeef9-399f-0af2-ba63-30bfe0efc4c3
* Content: [Multi-user capabilities tutorials - 5. Integrating Azure Spatial Anchors into a shared experience - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/tutorials/mr-learning-sharing-05)
* Content Source: [mixed-reality-docs/mr-dev-docs/develop/unity/tutorials/mr-learning-sharing-05.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-dev-docs/develop/unity/tutorials/mr-learning-sharing-05.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @jessemcculloch
* Microsoft Alias: **jemccull**

**Comment by martinwilter** [comment]
Hi @hwinstonuconn,

I checked the tutorial assets and the Button.prefab Y position is -0.1.

I think what happened is that you accidentally parented the Buttons to the SharedPlayground object:

![image](https://user-images.githubusercontent.com/16746283/95372794-ed087780-0890-11eb-9987-07b9d4b27a8c.png)

then reparented it to the TableAnchor object:

![image](https://user-images.githubusercontent.com/16746283/95372926-19bc8f00-0891-11eb-9b20-1a8699fea978.png)

Because the Y positions relative to the SharedPlayground object was -0.1 for the Button object and -0.55 for the TableAnchor object, the new local Y position for the Button object becomes (-0.1)-(-0.55) = 0.45.
__

@hferrone, I believe this issue can be closed.
