### ISSUE TITLE
Document whether MRTKv1 can be run on HoloLens 2 and whether MRTKv1 and MRTKv2 can be run side-by-side

### ISSUE THREAD

**Issue by ForrestTrepte** [MicrosoftDocs/mixed-reality#870]
After the first three steps (Unity, IL2CPP, ARM upgrades -- still on MRTKv1) can we run an app on HoloLens and expect to get it working? It wouldn't have any HoloLens 2 features such as fingers, but it might be helpful to get a legacy application running before porting to MRTKv2. Also, can MRTKv2 be added side-by-side while moving a piece at a time over from MRTKv1 to MRTKv2?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4ee0cfd0-8f75-e71c-a947-0f131e360ed5
* Version Independent ID: bf6057d7-09ca-be04-578b-af44aab5785c
* Content: [Getting your app ready for HoloLens 2 - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/mrtk-porting-guide)
* Content Source: [mixed-reality-docs/mrtk-porting-guide.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/mrtk-porting-guide.md)
* Product: **mixed-reality**
* GitHub Login: @author:grbury
* Microsoft Alias: **grbury**

**Comment by vmnetcetera** [comment]
Are there any news on this? Is it possible to run apps on HoloLens 2 without upgrading to MRTKv2?

**Comment by ForrestTrepte** [comment]
@vmnetcetera: I don't know if it is officially supported, but I have had success building and running MRTKv1 applications on HoloLens 2. Of course, after getting this working you'll probably want to upgrade in order to take advantage of the new hand interactions and other MRTKv2 goodness.

**Comment by jessemcculloch** [comment]
Yes, Applications using MRTK v1 can be run on an HL2 after changing the build target to ARM, assuming that all other requirements are met (ARM versions of plugins, etc). As Forest mentioned, you won't have HoloLens 2 specific functions such as articulated hand and eye tracking. Also, MRTK v1 and MRTK v2 have different namespaces so that both can be in the same project, which is useful for transitioning from one to the other.
